---
- name: Starting Apache Role
  debug:
    msg: "Installing, Starting and Enabling Apache"

- name: Including OS spesific tasks (Debian)
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'Debian'

- name: Including OS spesific tasks (RedHat)
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'RedHat'
