---
- name: Installing MySQL(Debian)
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    install_recommends: yes
  with_items:
    - mysql-client
    - mysql-server
  notify: Restart MySQL
