---
- name: Including OS spesific variables (RedHat)
  include_vars: "RedHat.yml"

- name: Install EPEL repo.
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ epel_version }}.noarch.rpm
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ epel_version }}
    state: present

- name: Installing MariaDB (RedHat)
  yum:
    name: "{{ item }}"
    state: present
    validate_certs: yes
  with_items:
    - mariadb
    - mariadb-server
  notify: Restart MySQL
